In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print('Dependencies: Imported siccessfully')

Dependencies: Imported siccessfully

In [ ]:
afr_entities = ['Algeria', 'Angola', 'Benin', 'Botswana', 'British Indian Ocean Territory',
                 'Burkina Faso', 'Burundi', 'Cameroon', 'Cape Verde', 'Central African Republic',
                 'Chad', 'Comoros', 'Congo', 'Djibouti', 'Egypt',
                 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon',
                 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Ivory Coast',
                 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar',
                 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Mayotte',
                 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria',
                 'Reunion', 'Rwanda', 'Saint Helena', 'Sao Tome and Principe', 'Senegal',
                 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan',
                 'Sudan', 'Tanzania', 'The Democratic Republic of Congo', 'Togo', 'Tunisia',
                 'Uganda', 'Western Sahara', 'Zambia', 'Zimbabwe']

In [2]:
dt1 = r"C:\Users\Etebom\Desktop\RGN_project\datasets\births-attended-by-health-staff-sdgs.csv"
dn1 = pd.read_csv(dt1)
df1 = 
dn1.head()

,Entity,Code,Year,Births attended by skilled health staff (% of total)
0,Afghanistan,AFG,2000,12.4
1,Afghanistan,AFG,2003,14.3
2,Afghanistan,AFG,2006,18.9
3,Afghanistan,AFG,2008,24.0
4,Afghanistan,AFG,2010,34.3

In [3]:
dt2 = r"C:\Users\Etebom\Desktop\RGN_project\datasets\child-mortality-by-income-level-of-country.csv"
dn2 = pd.read_csv(dt2)
dn2.head()

,Entity,Code,Year,Observation value - Indicator: Under-five mortality rate - Sex: Total - Wealth quintile: Total - Unit of measure: Deaths per 100 live births
0,Afghanistan,AFG,1957,37.245758
1,Afghanistan,AFG,1958,36.626625
2,Afghanistan,AFG,1959,36.043480
3,Afghanistan,AFG,1960,35.459850
4,Afghanistan,AFG,1961,34.894880

In [4]:
dt3 = r"C:\Users\Etebom\Desktop\RGN_project\datasets\Distribution of Causes of Death among Children Aged less than 5 years.csv"
dn3 = pd.read_csv(dt3)
dn3.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,MORT_300,Distribution of causes of death among children...,numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2017,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2018-11-26T23:00:00.000Z
1,MORT_300,Distribution of causes of death among children...,numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2017,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2018-11-26T23:00:00.000Z
2,MORT_300,Distribution of causes of death among children...,numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2017,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2018-11-26T23:00:00.000Z
3,MORT_300,Distribution of causes of death among children...,numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2017,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2018-11-26T23:00:00.000Z
4,MORT_300,Distribution of causes of death among children...,numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2017,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2018-11-26T23:00:00.000Z

In [5]:
dt = dn3[['Location', 'SpatialDimValueCode', 'Period', 'Dim2']].copy()

In [6]:
dt.rename(columns={
    'Location':'Entity',
    'SpatialDimValueCode': 'Code',
    'Period':'Year',
    'Dim2':'Cause of Death'
} ,
    inplace=True)

dt.columns

Index(['Entity', 'Code', 'Year', 'Cause of Death'], dtype='object')

In [7]:
dt4 = r"C:\Users\Etebom\Desktop\RGN_project\datasets\global-vaccination-coverage.csv"
dn4 = pd.read_csv(dt4)
dn4.head()

,Entity,Code,Year,BCG (% of one-year-olds immunized),HepB3 (% of one-year-olds immunized),Hib3 (% of one-year-olds immunized),IPV1 (% of one-year-olds immunized),MCV1 (% of one-year-olds immunized),PCV3 (% of one-year-olds immunized),Pol3 (% of one-year-olds immunized),RCV1 (% of one-year-olds immunized),RotaC (% of one-year-olds immunized),YFV (% of one-year-olds immunized),DTP3 (% of one-year-olds immunized)
0,Afghanistan,AFG,1982,10.0,NaN,NaN,NaN,8.0,NaN,5.0,NaN,NaN,NaN,5.0
1,Afghanistan,AFG,1983,10.0,NaN,NaN,NaN,9.0,NaN,5.0,NaN,NaN,NaN,5.0
2,Afghanistan,AFG,1984,11.0,NaN,NaN,NaN,14.0,NaN,16.0,NaN,NaN,NaN,16.0
3,Afghanistan,AFG,1985,17.0,NaN,NaN,NaN,14.0,NaN,15.0,NaN,NaN,NaN,15.0
4,Afghanistan,AFG,1986,18.0,NaN,NaN,NaN,14.0,NaN,11.0,NaN,NaN,NaN,11.0

In [8]:
dt5 = r"C:\Users\Etebom\Desktop\RGN_project\datasets\health-protection-coverage.csv"
dn5 = pd.read_csv(dt5)
dn5.head()

,Entity,Code,Year,Share of population covered by health insurance (ILO (2014))
0,Albania,ALB,2008,23.6
1,Algeria,DZA,2005,85.2
2,American Samoa,ASM,2009,3.0
3,Angola,AGO,2010,0.0
4,Antigua and Barbuda,ATG,2007,51.1

In [9]:
dt6 = r"C:\Users\Etebom\Desktop\RGN_project\datasets\number-of-infant-deaths-unwpp.csv"
dn6 = pd.read_csv(dt6)
dn6.head()

        Entity Code  Year  Deaths - Sex: all - Age: 0 - Variant: estimates
0  Afghanistan  AFG  1950                                         109220.0
1  Afghanistan  AFG  1951                                         107971.0
2  Afghanistan  AFG  1952                                         108140.0
3  Afghanistan  AFG  1953                                         108248.0
4  Afghanistan  AFG  1954                                         108241.0

In [10]:
dt7 = r"C:\Users\Etebom\Desktop\RGN_project\datasets\number-of-maternal-deaths-by-region.csv"
dn7 = pd.read_csv(dt7)
dn7.head()

        Entity Code  Year  Estimated maternal deaths 959828-annotations
0  Afghanistan  AFG  1985                 10258.5340                NaN
1  Afghanistan  AFG  1986                  8671.9210                NaN
2  Afghanistan  AFG  1987                  8488.9600                NaN
3  Afghanistan  AFG  1988                  7522.1216                NaN
4  Afghanistan  AFG  1989                  7549.7050                NaN

In [11]:
dt8 = r"C:\Users\Etebom\Desktop\RGN_project\datasets\youth-mortality-rate.csv"
dn8 = pd.read_csv(dt8)
dn8.head()

        Entity Code  Year  Under-fifteen mortality rate
0  Afghanistan  AFG  1977                     30.110573
1  Afghanistan  AFG  1978                     29.290777
2  Afghanistan  AFG  1979                     28.479010
3  Afghanistan  AFG  1980                     27.649078
4  Afghanistan  AFG  1981                     26.834482

In [12]:
dfs = [dn1, dn2, df, dn4, dn5, dn6, dn7, dn8]
dn = pd.concat(dfs)
dn.head()

,Entity,Code,Year,Births attended by skilled health staff (% of total),Observation value - Indicator: Under-five mortality rate - Sex: Total - Wealth quintile: Total - Unit of measure: Deaths per 100 live births,Cause of Death,BCG (% of one-year-olds immunized),HepB3 (% of one-year-olds immunized),Hib3 (% of one-year-olds immunized),IPV1 (% of one-year-olds immunized),...,Pol3 (% of one-year-olds immunized),RCV1 (% of one-year-olds immunized),RotaC (% of one-year-olds immunized),YFV (% of one-year-olds immunized),DTP3 (% of one-year-olds immunized),Share of population covered by health insurance (ILO (2014)),Deaths - Sex: all - Age: 0 - Variant: estimates,Estimated maternal deaths,959828-annotations,Under-fifteen mortality rate
0,Afghanistan,AFG,2000,12.4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2003,14.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,2006,18.9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,2008,24.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,2010,34.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
dn.rename(
    columns=
    {
        'Observation value - Indicator: Under-five mortality rate - Sex: Total - Wealth quintile: Total - Unit of measure: Deaths per 100 live births' : 'Under-five mortality rate (deaths per 100 live births)'
    }, inplace=True
)

In [14]:
dn.info()

<class 'pandas.core.frame.DataFrame'>
Index: 208423 entries, 0 to 10514
Data columns (total 22 columns):
 #   Column                                                        Non-Null Count   Dtype
---  ------                                                        --------------   -----
 0   Entity                                                        208423 non-null  object
 1   Code                                                          204056 non-null  object
 2   Year                                                          208423 non-null  int64
 3   Births attended by skilled health staff (% of total)          2985 non-null    float64
 4   Under-five mortality rate (deaths per 100 live births)        14200 non-null   float64
 5   Cause of Death                                                146664 non-null  object
 6   BCG (% of one-year-olds immunized)                            6497 non-null    float64
 7   HepB3 (% of one-year-olds immunized)                          4436 non-null    float64
 8   Hib3 (% of one-year-olds immunized)                           3629 non-null    float64
 9   IPV1 (% of one-year-olds immunized)                           1297 non-null    float64
 10  MCV1 (% of one-year-olds immunized)                           7728 non-null    float64
 11  PCV3 (% of one-year-olds immunized)                           1497 non-null    float64
 12  Pol3 (% of one-year-olds immunized)                           7855 non-null    float64
 13  RCV1 (% of one-year-olds immunized)                           4198 non-null    float64
 14  RotaC (% of one-year-olds immunized)                          1039 non-null    float64
 15  YFV (% of one-year-olds immunized)                            824 non-null     float64
 16  DTP3 (% of one-year-olds immunized)                           7854 non-null    float64
 17  Share of population covered by health insurance (ILO (2014))  162 non-null     float64
 18  Deaths - Sex: all - Age: 0 - Variant: estimates               18944 non-null   float64
 19  Estimated maternal deaths                                     7056 non-null    float64
 20  959828-annotations                                            36 non-null      object
 21  Under-fifteen mortality rate                                  10515 non-null   float64
dtypes: float64(17), int64(1), object(4)
memory usage: 36.6+ MB

In [15]:
dn = dn.drop('959828-annotations', axis=1)
dn.head()

,Entity,Code,Year,Births attended by skilled health staff (% of total),Under-five mortality rate (deaths per 100 live births),Cause of Death,BCG (% of one-year-olds immunized),HepB3 (% of one-year-olds immunized),Hib3 (% of one-year-olds immunized),IPV1 (% of one-year-olds immunized),...,PCV3 (% of one-year-olds immunized),Pol3 (% of one-year-olds immunized),RCV1 (% of one-year-olds immunized),RotaC (% of one-year-olds immunized),YFV (% of one-year-olds immunized),DTP3 (% of one-year-olds immunized),Share of population covered by health insurance (ILO (2014)),Deaths - Sex: all - Age: 0 - Variant: estimates,Estimated maternal deaths,Under-fifteen mortality rate
0,Afghanistan,AFG,2000,12.4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2003,14.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,2006,18.9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,2008,24.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,2010,34.3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
dn.shape

(208423, 21)

In [28]:
dn.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,208423.0,2004.191006,1.304579e+01,1932.000000,2001.000000,2007.000000,2013.000000,2.023000e+03
Births attended by skilled health staff (% of total),2985.0,88.926417,2.015661e+01,5.000000,90.000000,98.700000,99.780000,1.000000e+02
Under-five mortality rate (deaths per 100 live births),14200.0,8.009897,8.409812e+00,0.146058,1.811918,4.703670,11.561593,5.714969e+01
BCG (% of one-year-olds immunized),6497.0,84.010312,2.000947e+01,0.000000,79.000000,92.000000,98.000000,9.900000e+01
HepB3 (% of one-year-olds immunized),4436.0,82.326195,2.192425e+01,0.000000,77.000000,91.000000,96.000000,9.900000e+01
Hib3 (% of one-year-olds immunized),3629.0,83.148250,2.203287e+01,0.000000,80.000000,92.000000,96.000000,9.900000e+01
IPV1 (% of one-year-olds immunized),1297.0,82.730146,2.268534e+01,0.000000,76.000000,94.000000,98.000000,9.900000e+01
MCV1 (% of one-year-olds immunized),7728.0,78.443323,2.189540e+01,0.000000,68.000000,87.000000,95.000000,9.900000e+01
PCV3 (% of one-year-olds immunized),1497.0,77.035404,2.489769e+01,0.000000,69.000000,87.000000,94.000000,9.900000e+01
Pol3 (% of one-year-olds immunized),7855.0,80.095226,2.211455e+01,0.000000,72.000000,89.000000,96.000000,9.900000e+01
RCV1 (% of one-year-olds immunized),4198.0,85.676513,2.101028e+01,0.000000,85.000000,93.000000,97.000000,9.900000e+01
RotaC (% of one-year-olds immunized),1039.0,69.495669,2.813773e+01,0.000000,58.000000,80.000000,90.000000,9.900000e+01
YFV (% of one-year-olds immunized),824.0,54.274272,2.890375e+01,0.000000,35.000000,60.000000,79.250000,9.900000e+01
DTP3 (% of one-year-olds immunized),7854.0,79.543672,2.222026e+01,1.000000,71.000000,88.000000,96.000000,9.900000e+01
Share of population covered by health insurance (ILO (2014)),162.0,62.507407,3.955700e+01,0.000000,23.000000,83.500000,100.000000,1.000000e+02
Deaths - Sex: all - Age: 0 - Variant: estimates,18944.0,246156.674416,1.198653e+06,0.000000,184.000000,3023.000000,28610.250000,1.351450e+07
Estimated maternal deaths,7056.0,8661.259033,4.382066e+04,0.061462,9.854105,127.637903,1664.778900,5.782459e+05
Under-fifteen mortality rate,10515.0,6.407323,6.958859e+00,0.190339,1.670638,3.532842,8.704788,5.958648e+01

In [29]:
dn.isnull().sum()

Entity                                                               0
Code                                                              4367
Year                                                                 0
Births attended by skilled health staff (% of total)            205438
Under-five mortality rate (deaths per 100 live births)          194223
Cause of Death                                                   61759
BCG (% of one-year-olds immunized)                              201926
HepB3 (% of one-year-olds immunized)                            203987
Hib3 (% of one-year-olds immunized)                             204794
IPV1 (% of one-year-olds immunized)                             207126
MCV1 (% of one-year-olds immunized)                             200695
PCV3 (% of one-year-olds immunized)                             206926
Pol3 (% of one-year-olds immunized)                             200568
RCV1 (% of one-year-olds immunized)                             204225
RotaC (% of one-year-olds immunized)                            207384
YFV (% of one-year-olds immunized)                              207599
DTP3 (% of one-year-olds immunized)                             200569
Share of population covered by health insurance (ILO (2014))    208261
Deaths - Sex: all - Age: 0 - Variant: estimates                 189479
Estimated maternal deaths                                       201367
Under-fifteen mortality rate                                    197908
dtype: int64

In [30]:
(dn.isnull().mean() * 100).round(2)

Entity                                                           0.00
Code                                                             2.10
Year                                                             0.00
Births attended by skilled health staff (% of total)            98.57
Under-five mortality rate (deaths per 100 live births)          93.19
Cause of Death                                                  29.63
BCG (% of one-year-olds immunized)                              96.88
HepB3 (% of one-year-olds immunized)                            97.87
Hib3 (% of one-year-olds immunized)                             98.26
IPV1 (% of one-year-olds immunized)                             99.38
MCV1 (% of one-year-olds immunized)                             96.29
PCV3 (% of one-year-olds immunized)                             99.28
Pol3 (% of one-year-olds immunized)                             96.23
RCV1 (% of one-year-olds immunized)                             97.99
RotaC (% of one-year-olds immunized)                            99.50
YFV (% of one-year-olds immunized)                              99.60
DTP3 (% of one-year-olds immunized)                             96.23
Share of population covered by health insurance (ILO (2014))    99.92
Deaths - Sex: all - Age: 0 - Variant: estimates                 90.91
Estimated maternal deaths                                       96.61
Under-fifteen mortality rate                                    94.95
dtype: float64

In [17]:
afr_entities = ['Algeria', 'Angola', 'Benin', 'Botswana', 'British Indian Ocean Territory',
                 'Burkina Faso', 'Burundi', 'Cameroon', 'Cape Verde', 'Central African Republic',
                 'Chad', 'Comoros', 'Congo', 'Djibouti', 'Egypt',
                 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Gabon',
                 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Ivory Coast',
                 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar',
                 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Mayotte',
                 'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria',
                 'Reunion', 'Rwanda', 'Saint Helena', 'Sao Tome and Principe', 'Senegal',
                 'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan',
                 'Sudan', 'Tanzania', 'The Democratic Republic of Congo', 'Togo', 'Tunisia',
                 'Uganda', 'Western Sahara', 'Zambia', 'Zimbabwe']

In [23]:
df = dn[dn['Entity'].isin(afr_entities)].copy()
df.head()

,Entity,Code,Year,Births attended by skilled health staff (% of total),Under-five mortality rate (deaths per 100 live births),Cause of Death,BCG (% of one-year-olds immunized),HepB3 (% of one-year-olds immunized),Hib3 (% of one-year-olds immunized),IPV1 (% of one-year-olds immunized),...,PCV3 (% of one-year-olds immunized),Pol3 (% of one-year-olds immunized),RCV1 (% of one-year-olds immunized),RotaC (% of one-year-olds immunized),YFV (% of one-year-olds immunized),DTP3 (% of one-year-olds immunized),Share of population covered by health insurance (ILO (2014)),Deaths - Sex: all - Age: 0 - Variant: estimates,Estimated maternal deaths,Under-fifteen mortality rate
32,Algeria,DZA,1992,76.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Algeria,DZA,2000,92.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Algeria,DZA,2002,95.9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Algeria,DZA,2006,95.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Algeria,DZA,2013,96.6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51997 entries, 32 to 10514
Data columns (total 21 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Entity                                                        51997 non-null  object
 1   Code                                                          51997 non-null  object
 2   Year                                                          51997 non-null  int64
 3   Births attended by skilled health staff (% of total)          404 non-null    float64
 4   Under-five mortality rate (deaths per 100 live births)        3394 non-null   float64
 5   Cause of Death                                                37800 non-null  object
 6   BCG (% of one-year-olds immunized)                            2008 non-null   float64
 7   HepB3 (% of one-year-olds immunized)                          970 non-null    float64
 8   Hib3 (% of one-year-olds immunized)                           749 non-null    float64
 9   IPV1 (% of one-year-olds immunized)                           302 non-null    float64
 10  MCV1 (% of one-year-olds immunized)                           1993 non-null   float64
 11  PCV3 (% of one-year-olds immunized)                           383 non-null    float64
 12  Pol3 (% of one-year-olds immunized)                           2003 non-null   float64
 13  RCV1 (% of one-year-olds immunized)                           288 non-null    float64
 14  RotaC (% of one-year-olds immunized)                          306 non-null    float64
 15  YFV (% of one-year-olds immunized)                            440 non-null    float64
 16  DTP3 (% of one-year-olds immunized)                           2002 non-null   float64
 17  Share of population covered by health insurance (ILO (2014))  37 non-null     float64
 18  Deaths - Sex: all - Age: 0 - Variant: estimates               4144 non-null   float64
 19  Estimated maternal deaths                                     1872 non-null   float64
 20  Under-fifteen mortality rate                                  2324 non-null   float64
dtypes: float64(17), int64(1), object(3)
memory usage: 8.7+ MB

In [25]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,51997.0,2004.528261,12.596604,1932.000000,2002.000000,2007.000000,2013.000000,2023.000000
Births attended by skilled health staff (% of total),404.0,62.972772,25.720088,5.000000,43.875000,60.800000,86.675000,100.000000
Under-five mortality rate (deaths per 100 live births),3394.0,15.368125,9.129506,1.033715,8.040390,13.927085,21.549682,42.630410
BCG (% of one-year-olds immunized),2008.0,80.329183,20.598439,2.000000,72.000000,88.000000,95.000000,99.000000
HepB3 (% of one-year-olds immunized),970.0,80.765979,17.779230,1.000000,74.000000,87.000000,94.000000,99.000000
Hib3 (% of one-year-olds immunized),749.0,80.427236,17.721678,1.000000,73.000000,87.000000,94.000000,99.000000
IPV1 (% of one-year-olds immunized),302.0,68.238411,25.447545,0.000000,49.250000,74.000000,90.000000,99.000000
MCV1 (% of one-year-olds immunized),1993.0,68.243853,22.528156,1.000000,53.000000,73.000000,87.000000,99.000000
PCV3 (% of one-year-olds immunized),383.0,76.417755,20.833745,1.000000,67.000000,83.000000,91.500000,99.000000
Pol3 (% of one-year-olds immunized),2003.0,68.923615,24.927801,1.000000,52.500000,75.000000,89.000000,99.000000
RCV1 (% of one-year-olds immunized),288.0,89.166667,11.037787,29.000000,87.000000,92.000000,97.000000,99.000000
RotaC (% of one-year-olds immunized),306.0,77.202614,20.705384,2.000000,68.000000,85.000000,91.000000,99.000000
YFV (% of one-year-olds immunized),440.0,58.186364,24.418556,1.000000,41.000000,63.000000,78.000000,97.000000
DTP3 (% of one-year-olds immunized),2002.0,68.988012,25.017892,1.000000,51.000000,77.000000,89.000000,99.000000
Share of population covered by health insurance (ILO (2014)),37.0,28.313514,33.982358,0.000000,2.100000,9.000000,42.300000,100.000000
Deaths - Sex: all - Age: 0 - Variant: estimates,4144.0,38620.213315,72940.338656,0.000000,2538.500000,19897.000000,46720.250000,608109.000000
Estimated maternal deaths,1872.0,3925.906654,9601.377272,0.061462,282.952058,1682.867600,3966.900600,86380.270000
Under-fifteen mortality rate,2324.0,13.794257,8.268491,1.274650,7.430877,12.234694,19.425306,59.586483

In [32]:
df.isnull().mean()

Entity                                                          0.000000
Code                                                            0.000000
Year                                                            0.000000
Births attended by skilled health staff (% of total)            0.992230
Under-five mortality rate (deaths per 100 live births)          0.934727
Cause of Death                                                  0.273035
BCG (% of one-year-olds immunized)                              0.961382
HepB3 (% of one-year-olds immunized)                            0.981345
Hib3 (% of one-year-olds immunized)                             0.985595
IPV1 (% of one-year-olds immunized)                             0.994192
MCV1 (% of one-year-olds immunized)                             0.961671
PCV3 (% of one-year-olds immunized)                             0.992634
Pol3 (% of one-year-olds immunized)                             0.961479
RCV1 (% of one-year-olds immunized)                             0.994461
RotaC (% of one-year-olds immunized)                            0.994115
YFV (% of one-year-olds immunized)                              0.991538
DTP3 (% of one-year-olds immunized)                             0.961498
Share of population covered by health insurance (ILO (2014))    0.999288
Deaths - Sex: all - Age: 0 - Variant: estimates                 0.920303
Estimated maternal deaths                                       0.963998
Under-fifteen mortality rate                                    0.955305
dtype: float64

In [31]:
(df.isnull().mean() * 100).round(2)

Entity                                                           0.00
Code                                                             0.00
Year                                                             0.00
Births attended by skilled health staff (% of total)            99.22
Under-five mortality rate (deaths per 100 live births)          93.47
Cause of Death                                                  27.30
BCG (% of one-year-olds immunized)                              96.14
HepB3 (% of one-year-olds immunized)                            98.13
Hib3 (% of one-year-olds immunized)                             98.56
IPV1 (% of one-year-olds immunized)                             99.42
MCV1 (% of one-year-olds immunized)                             96.17
PCV3 (% of one-year-olds immunized)                             99.26
Pol3 (% of one-year-olds immunized)                             96.15
RCV1 (% of one-year-olds immunized)                             99.45
RotaC (% of one-year-olds immunized)                            99.41
YFV (% of one-year-olds immunized)                              99.15
DTP3 (% of one-year-olds immunized)                             96.15
Share of population covered by health insurance (ILO (2014))    99.93
Deaths - Sex: all - Age: 0 - Variant: estimates                 92.03
Estimated maternal deaths                                       96.40
Under-fifteen mortality rate                                    95.53
dtype: float64

In [40]:
df_u5 = df.groupby('Entity', as_index=False)['Under-five mortality rate (deaths per 100 live births)'].sum()
df_u5_sorted = df_u5.sort_values(by='Under-five mortality rate (deaths per 100 live births)', ascending=False) 
df_u5_sorted.head()

          Entity  Under-five mortality rate (deaths per 100 live births)
21        Guinea                                        2206.498029
4   Burkina Faso                                        1903.583849
44  Sierra Leone                                        1725.104848
47   South Sudan                                        1650.220149
2          Benin                                        1636.001028

In [46]:
fltd = df[(df['Under-five mortality rate (deaths per 100 live births)']!=0) & (df['Under-five mortality rate (deaths per 100 live births)'].notnull())]
df_cod = fltd.groupby('Cause of Death', as_index=False)['Under-five mortality rate (deaths per 100 live births)'].max()
df_cod_sorted = df_cod.sort_values(by='Under-five mortality rate (deaths per 100 live births)', ascending=False)
df_cod_sorted.head()

Empty DataFrame
Columns: [Cause of Death, Under-five mortality rate (deaths per 100 live births)]
Index: []

In [48]:
fltd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3394 entries, 202 to 14199
Data columns (total 21 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Entity                                                        3394 non-null   object
 1   Code                                                          3394 non-null   object
 2   Year                                                          3394 non-null   int64
 3   Births attended by skilled health staff (% of total)          0 non-null      float64
 4   Under-five mortality rate (deaths per 100 live births)        3394 non-null   float64
 5   Cause of Death                                                0 non-null      object
 6   BCG (% of one-year-olds immunized)                            0 non-null      float64
 7   HepB3 (% of one-year-olds immunized)                          0 non-null      float64
 8   Hib3 (% of one-year-olds immunized)                           0 non-null      float64
 9   IPV1 (% of one-year-olds immunized)                           0 non-null      float64
 10  MCV1 (% of one-year-olds immunized)                           0 non-null      float64
 11  PCV3 (% of one-year-olds immunized)                           0 non-null      float64
 12  Pol3 (% of one-year-olds immunized)                           0 non-null      float64
 13  RCV1 (% of one-year-olds immunized)                           0 non-null      float64
 14  RotaC (% of one-year-olds immunized)                          0 non-null      float64
 15  YFV (% of one-year-olds immunized)                            0 non-null      float64
 16  DTP3 (% of one-year-olds immunized)                           0 non-null      float64
 17  Share of population covered by health insurance (ILO (2014))  0 non-null      float64
 18  Deaths - Sex: all - Age: 0 - Variant: estimates               0 non-null      float64
 19  Estimated maternal deaths                                     0 non-null      float64
 20  Under-fifteen mortality rate                                  0 non-null      float64
dtypes: float64(17), int64(1), object(3)
memory usage: 583.3+ KB

,Entity,Code,Year,Births attended by skilled health staff (% of total),Under-five mortality rate (deaths per 100 live births),Cause of Death,BCG (% of one-year-olds immunized),HepB3 (% of one-year-olds immunized),Hib3 (% of one-year-olds immunized),IPV1 (% of one-year-olds immunized),...,PCV3 (% of one-year-olds immunized),Pol3 (% of one-year-olds immunized),RCV1 (% of one-year-olds immunized),RotaC (% of one-year-olds immunized),YFV (% of one-year-olds immunized),DTP3 (% of one-year-olds immunized),Share of population covered by health insurance (ILO (2014)),Deaths - Sex: all - Age: 0 - Variant: estimates,Estimated maternal deaths,Under-fifteen mortality rate
32,Algeria,DZA,1992,76.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Algeria,DZA,2000,92.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Algeria,DZA,2002,95.9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Algeria,DZA,2006,95.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Algeria,DZA,2013,96.6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10510,Zimbabwe,ZWE,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.515447
10511,Zimbabwe,ZWE,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.387253
10512,Zimbabwe,ZWE,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.259883
10513,Zimbabwe,ZWE,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.999933
10514,Zimbabwe,ZWE,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.834957

In [13]:
dn.columns

Index(['Entity', 'Code', 'Year',
       'Births attended by skilled health staff (% of total)',
       'Observation value - Indicator: Under-five mortality rate - Sex: Total - Wealth quintile: Total - Unit of measure: Deaths per 100 live births',
       'Cause of Death', 'BCG (% of one-year-olds immunized)',
       'HepB3 (% of one-year-olds immunized)',
       'Hib3 (% of one-year-olds immunized)',
       'IPV1 (% of one-year-olds immunized)',
       'MCV1 (% of one-year-olds immunized)',
       'PCV3 (% of one-year-olds immunized)',
       'Pol3 (% of one-year-olds immunized)',
       'RCV1 (% of one-year-olds immunized)',
       'RotaC (% of one-year-olds immunized)',
       'YFV (% of one-year-olds immunized)',
       'DTP3 (% of one-year-olds immunized)',
       'Share of population covered by health insurance (ILO (2014))',
       'Deaths - Sex: all - Age: 0 - Variant: estimates',
       'Estimated maternal deaths', '959828-annotations',
       'Under-fifteen mortality rate'],
      dtype='object')

The columns in the dataframe 'dn' represent various health-related indicators and demographic information, typically used in global health datasets like those from the **World Health Organization (WHO)**, **United Nations**, or **World Bank**. Here’s a description of each column:

### **Entity**  
   - This typically refers to the name of the country, region, or other administrative unit in the dataset. It represents the geographical or political entity where the data is collected from (e.g., "United States", "India", "World").

### **Code**  
   - This is likely a unique identifier or code for each country or region in the dataset (e.g., a country code like "USA" for the United States or "IN" for India). It is used for referencing the entity more efficiently.

### **Year**  
   - This column indicates the year in which the data was collected or reported (e.g., "2020", "2021"). This is important for time series analysis to track changes over time.

### **Births attended by skilled health staff (% of total)**  
   - This percentage represents the proportion of births in a specific country or region that are attended by skilled health personnel (doctors, nurses, midwives) during delivery. It is an important indicator of maternal health services.

### **Observation value - Indicator: Under-five mortality rate - Sex: Total - Wealth quintile: Total - Unit of measure: Deaths per 100 live births**  
   - This indicator shows the under-five mortality rate, which is the probability of a child dying before reaching the age of five, per 100 live births. It is an important health metric used to measure child health and development. The column also suggests that this is a general estimate for all sexes and wealth quintiles.

### **Cause of Death**  
   - This column indicates the specific cause of death (e.g., "Malaria", "Pneumonia", "Heart Disease") for which the data is being reported. This can be used for analyzing the leading causes of death in different regions or populations.

### Immunization Indicators (Columns 7-16)  
   These columns contain the percentage of one-year-olds who are vaccinated with specific vaccines:

   - **BCG (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the **Bacillus Calmette-Guérin (BCG)** vaccine, which is primarily used to protect against tuberculosis (TB).
   
   - **HepB3 (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the third dose of the **Hepatitis B** vaccine, which prevents Hepatitis B infection.

   - **Hib3 (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the third dose of the **Haemophilus influenzae type b (Hib)** vaccine, which helps prevent infections like meningitis and pneumonia.

   - **IPV1 (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the first dose of the **Inactivated Polio Vaccine (IPV)** to prevent polio.

   - **MCV1 (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the first dose of the **Measles Containing Vaccine (MCV1)**, which is important for measles prevention.

   - **PCV3 (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the third dose of the **Pneumococcal Conjugate Vaccine (PCV3)**, which helps prevent pneumonia, meningitis, and other infections caused by Streptococcus pneumoniae.

   - **Pol3 (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the third dose of the **Polio** vaccine, which protects against polio virus infection.

   - **RCV1 (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the first dose of the **Rotavirus vaccine (RCV1)**, which prevents severe diarrhea caused by rotavirus.

   - **RotaC (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with a **rotavirus vaccine**. This is sometimes denoted as **RotaC** for a particular version of the vaccine.

   - **YFV (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the **Yellow Fever Vaccine (YFV)**, which is essential in regions with risk for yellow fever transmission.

   - **DTP3 (% of one-year-olds immunized)**:  
     Percentage of one-year-olds immunized with the third dose of the **Diphtheria, Tetanus, and Pertussis (DTP3)** vaccine. This vaccine prevents these three serious diseases.

### **Share of population covered by health insurance (ILO (2014))**  
   - This percentage represents the proportion of the population in a given country or region that is covered by **health insurance**, based on data from the **International Labour Organization (ILO)** in 2014. It provides insights into access to healthcare services and social protection.

### **Deaths - Sex: all - Age: 0 - Variant: estimates**  
   - This column contains the estimated number of **deaths among all sexes for individuals aged 0** (i.e., infant and child mortality) based on available data. This measure is often used to assess child mortality trends.

### **Estimated maternal deaths**  
   - This represents the estimated number of **maternal deaths**, typically defined as deaths resulting from complications during pregnancy, childbirth, or within a certain period after childbirth. This indicator is crucial for assessing maternal health and the quality of healthcare available to women during pregnancy and childbirth.

### **959828-annotations**  
   - This column may contain special annotations or metadata associated with the dataset, such as notes, comments, or additional references. The specific code **959828** could refer to a particular dataset, version, or source, but it requires more context to understand fully.

### **Under-fifteen mortality rate**  
   - This represents the **under-fifteen mortality rate**, which is the number of deaths of children under 15 years of age per 1,000 live births. This is another key indicator of child health and overall health system effectiveness.


### Summary
These columns represent various **health indicators** related to maternal and child health, immunization coverage, and mortality rates. They provide insights into the effectiveness of healthcare systems in a given region or country, helping policymakers and organizations track health progress and identify areas needing improvement.